export const CLI_COMMAND_TIMEOUT_MS = 3_000;
export const POST_TOOL_USE_FEEDBACK_SAMPLE_RATE = 0.99;
export const STOP_FEEDBACK_SAMPLE_RATE = 0.99;
export const TRANSCRIPT_READ_CHUNK_BYTES = 64 * 1024;
